// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUzHnJI_UjKUS_CdfpTN3mAVsoTsYun7A',
    appId: '1:576869970938:web:1bdb38fe3e08830ce3ea43',
    messagingSenderId: '576869970938',
    projectId: 'webapicuresee',
    authDomain: 'webapicuresee.firebaseapp.com',
    storageBucket: 'webapicuresee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_sZ-gPCgbTqnvx5i4BI-1TolyD7K6pdc',
    appId: '1:576869970938:android:14ebbc01ac9c86a9e3ea43',
    messagingSenderId: '576869970938',
    projectId: 'webapicuresee',
    storageBucket: 'webapicuresee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw4yVbCMNxhWbZtwq4WydxTY-G2FppHAA',
    appId: '1:576869970938:ios:3a54be591c65b090e3ea43',
    messagingSenderId: '576869970938',
    projectId: 'webapicuresee',
    storageBucket: 'webapicuresee.firebasestorage.app',
    iosBundleId: 'com.example.curesee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw4yVbCMNxhWbZtwq4WydxTY-G2FppHAA',
    appId: '1:576869970938:ios:3a54be591c65b090e3ea43',
    messagingSenderId: '576869970938',
    projectId: 'webapicuresee',
    storageBucket: 'webapicuresee.firebasestorage.app',
    iosBundleId: 'com.example.curesee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUzHnJI_UjKUS_CdfpTN3mAVsoTsYun7A',
    appId: '1:576869970938:web:adcc84914e080694e3ea43',
    messagingSenderId: '576869970938',
    projectId: 'webapicuresee',
    authDomain: 'webapicuresee.firebaseapp.com',
    storageBucket: 'webapicuresee.firebasestorage.app',
  );
}
